# Generated by Django 5.1.6 on 2025-02-27 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_address_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='primary_doctor',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
        migrations.DeleteModel(
            name='PatientProfile',
        ),
    ]
