# Generated by Django 5.1.6 on 2025-03-10 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_patientprofile_primary_doctor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
