# Generated by Django 5.1.7 on 2025-04-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fitbitvitals'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitbitvitals',
            name='body_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitbitvitals',
            name='sleep_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitbitvitals',
            name='spo2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
