# Generated by Django 5.1.6 on 2025-03-10 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_patient_role_doctor'),
        ('recovery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recoverytip',
            name='patient',
        ),
        migrations.AddField(
            model_name='recoverytip',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notifications.doctor'),
            preserve_default=False,
        ),
    ]
