# Generated by Django 5.1.7 on 2025-03-20 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_appointment_doctor_name_appointment_doctor'),
        ('recovery', '0002_remove_recoverytip_patient_recoverytip_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverytip',
            name='patient',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='notifications.patient'),
            preserve_default=False,
        ),
    ]
