# Generated by Django 5.1.6 on 2025-03-11 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_patient_role_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.doctor'),
        ),
    ]
