# Generated by Django 5.1.7 on 2025-04-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_appointment_doctor_name_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='fitbit_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fitbit_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='fitbit_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
