# Generated by Django 5.1.7 on 2025-04-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_patient_fitbit_access_token_patient_fitbit_connected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_available_for_call',
            field=models.BooleanField(default=False),
        ),
    ]
