# Generated by Django 5.1.7 on 2025-04-10 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_prescription_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultrequest',
            name='prescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.prescription'),
        ),
    ]
