# Generated by Django 5.1.7 on 2025-04-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_consultrequest_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultrequest',
            name='room_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
