# Generated by Django 5.1.7 on 2025-04-17 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_consultrequest_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationschedule',
            name='duration_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='food_timing',
            field=models.CharField(choices=[('before', 'Before Food'), ('after', 'After Food'), ('with', 'With Food')], default='after', max_length=50),
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('diagnosis', models.TextField()),
                ('symptoms', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='notifications.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistoryMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=255)),
                ('duration_days', models.PositiveIntegerField()),
                ('food_timing', models.CharField(choices=[('before', 'Before Food'), ('after', 'After Food'), ('with', 'With Food')], max_length=50)),
                ('medical_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='notifications.medicalhistory')),
            ],
        ),
    ]
