# Generated by Django 5.1.7 on 2025-04-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_patientfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientfeedback',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='patientfeedback',
            name='sentiment_score',
        ),
        migrations.AddField(
            model_name='patientfeedback',
            name='consultation_accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientfeedback',
            name='consultation_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientfeedback',
            name='doctor_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientfeedback',
            name='follow_up_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientfeedback',
            name='next_steps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientfeedback',
            name='pain_level',
            field=models.IntegerField(blank=True, help_text='Pain level from 0-10', null=True),
        ),
        migrations.AddField(
            model_name='patientfeedback',
            name='reasoning',
            field=models.TextField(default='No specific reasoning provided'),
        ),
        migrations.AddField(
            model_name='patientfeedback',
            name='severity_level',
            field=models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='mild', max_length=20),
        ),
        migrations.AddField(
            model_name='patientfeedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patientfeedback',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientfeedback',
            name='sentiment_label',
            field=models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=20),
        ),
    ]
