# Generated by Django 5.1.7 on 2025-04-20 06:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0017_appointment_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationschedule',
            name='last_reminder_time',
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='last_status_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='reminder_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('taken', 'Taken'), ('overdue', 'Overdue'), ('missed', 'Missed')], default='pending', max_length=10),
        ),
    ]
