# Generated by Django 5.1.7 on 2025-04-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0018_remove_medicationschedule_last_reminder_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationschedule',
            name='reminder_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('taken', 'Taken'), ('overdue', 'Overdue'), ('missed', 'Missed'), ('ended', 'Ended')], default='pending', max_length=10),
        ),
    ]
