# Generated by Django 5.1.7 on 2025-04-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0019_alter_medicationschedule_reminder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientfeedback',
            name='viewed_by_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
