# Generated by Django 5.1.7 on 2025-04-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0020_patientfeedback_viewed_by_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultrequest',
            name='viewed_by_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
